const categoriasCardapio = [
    {
        id: "agua",
        nome: "Água",
        itens: [
            { id: 103, nome: "Água Sem Gás 1,5L", desc: "Garrafa", preco: 5.00, img: "água/agua_sem_gas_1,5_L_.jpg" },
            { id: 104, nome: "Água Com Gás 1,5L", desc: "Garrafa", preco: 5.00, img: "água/agua_com_gas_1,5_lt.jpg" },
            { id: 101, nome: "Água Sem Gás 500ml", desc: "Garrafa", preco: 2.50, img: "água/agua_sem_gas_500_ml.jpg" },
            { id: 102, nome: "Água Com Gás 500ml", desc: "Garrafa", preco: 3.00, img: "água/agua_com_gas_500_ml_.jpg" }
        ]
    },
    {
        id: "bebidas-alcolicas",
        nome: "Destilados",
        itens: [
            { id: 301, nome: "Whisky Red Label", desc: "1 Litro", preco: 100.00, img: "destilados/whisky_red_label_1_L_.jpg" },
            { id: 302, nome: "Whisky White Horse", desc: "1 Litro", preco: 90.00, img: "destilados/whisky_white_horse_1_L_.jpg" },
            { id: 303, nome: "Whisky Royal Blue", desc: "1 Litro", preco: 25.00, img: "destilados/whisky_royal_blue_1_L_.jpg" },
            { id: 304, nome: "Vodka Smirnoff", desc: "998ml", preco: 50.00, img: "destilados/vodka_smirnoff_998_ml_.jpg" },
            { id: 305, nome: "Vodka Swarovski", desc: "965ml", preco: 16.00, img: "destilados/vodka_swarovski_965_ml_.jpg" },
            { id: 306, nome: "Vodka Leonoff", desc: "900ml", preco: 20.00, img: "destilados/vodka_leonoff_900_ml_.jpg" },
            { id: 307, nome: "Cachaça 51", desc: "965ml", preco: 9.00, img: "destilados/51_965_ml_.jpg" },
            { id: 308, nome: "Whisky da Mansão", desc: "1 Litro", preco: 30.00, img: "destilados/whisky_da_mansão_1_L_.jpg" },
            { id: 309, nome: "Whisky + Combo", desc: "1L Coquetel", preco: 25.00, img: "destilados/whisky_+_combo_1_L_coquetel_.jpg" },
            { id: 310, nome: "Vodka + Combo", desc: "1L Coquetel", preco: 25.00, img: "destilados/vodka_+_combo_1_L_Coquetel_.jpg" },
            { id: 311, nome: "GinKut Original Mansão", desc: "1 Litro", preco: 25.00, img: "destilados/ginKut_original_mansao_1_L_.jpg" },
            { id: 312, nome: "Vinho Pérgola", desc: "1 Litro", preco: 25.00, img: "destilados/vinho_pérgola_1_L_.jpg" },
            { id: 313, nome: "Vinho Quinta do Morgado", desc: "1 Litro", preco: 20.00, img: "destilados/vinho_quinta_do_morgado_1_L_.jpg" }
        ]
    },
    {
        id: "carvao",
        nome: "Carvão",
        itens: [
            { id: 402, nome: "Carvão Brasa do Vale 5kg", desc: "Saco", preco: 26.00, img: "carvão/carvao_brasa_do_vale_5_kg_.jpg" },
            { id: 401, nome: "Carvão Brasa do Vale 3kg", desc: "Saco", preco: 16.00, img: "carvão/carvao_brasa_do_vale_3_kg_.jpg" }
        ]
    },
    {
        id: "cervejas",
        nome: "Cervejas",
        itens: [
            { id: 13, nome: "Skol Litrão", desc: "1 Litro", preco: 9.00, img: "cerveja/cerfeja_skol_litrao_.jpg" },
            { id: 14, nome: "Amstel Litrão", desc: "1 Litro", preco: 10.00, img: "cerveja/cerveja_amistel_litrao_.jpg" },
            { id: 15, nome: "Antarctica Litrão", desc: "1 Litro", preco: 9.00, img: "cerveja/cerveja_antarctica_litrao_.jpg" },
            { id: 16, nome: "Brahma Litrão", desc: "1 Litro", preco: 9.00, img: "cerveja/cerveja_brahama_litrao_.jpg" },
            { id: 17, nome: "Budweiser Litrão", desc: "1 Litro", preco: 9.00, img: "cerveja/cerveja_budweiser_litrao_.jpg" },
            { id: 18, nome: "Itaipava Litrão", desc: "1 Litro", preco: 8.00, img: "cerveja/cerveja_itaipava_litrao.jpg" },
            { id: 43, nome: "Antarctica Mega Latão", desc: "550ml", preco: 7.50, img: "cerveja/mega_latao_antarctica_550_ml_.jpg" },
            { id: 44, nome: "Brahma Mega Latão", desc: "550ml", preco: 7.50, img: "cerveja/mega_latao_brahma_550_ml_.jpg" },
            { id: 45, nome: "Itaipava Mega Latão", desc: "550ml", preco: 6.50, img: "cerveja/mega_latao_itaipava_550_ml_.jpg" },
            { id: 51, nome: "Skol Mega Latão", desc: "550ml", preco: 7.00, img: "cerveja/skol_550_ml_.jpg" },
            { id: 2, nome: "Amstel 600ml", desc: "Garrafa", preco: 8.00, img: "cerveja/amstel_600_ml_.jpg" },
            { id: 5, nome: "Antarctica 600ml", desc: "Garrafa", preco: 7.00, img: "cerveja/antarctica_600_ml_.jpg" },
            { id: 8, nome: "Brahma 600ml", desc: "Garrafa", preco: 7.00, img: "cerveja/brahma_600_ml_.jpg" },
            { id: 11, nome: "Budweiser 600ml", desc: "Garrafa", preco: 8.00, img: "cerveja/budweiser_600_ml_.jpg" },
            { id: 20, nome: "Eisenbahn 600ml", desc: "Garrafa", preco: 9.00, img: "cerveja/eisenbahn_600_ml_.jpg" },
            { id: 22, nome: "Heineken 600ml", desc: "Garrafa", preco: 13.00, img: "cerveja/heineken_600_ml_.jpg" },
            { id: 27, nome: "Itaipava 600ml", desc: "Garrafa", preco: 7.00, img: "cerveja/itaipava_600_ml_.jpg" },
            { id: 52, nome: "Skol 600ml", desc: "Garrafa", preco: 7.00, img: "cerveja/skol_600_ml_.jpg" },
            { id: 53, nome: "Spaten 600ml", desc: "Garrafa", preco: 10.00, img: "cerveja/spaten_600_ml_.jpg" },
            { id: 1, nome: "Amstel Latão", desc: "473ml", preco: 6.50, img: "cerveja/amistel_latao_473_ml_.jpg" },
            { id: 6, nome: "Antarctica Latão", desc: "473ml", preco: 6.00, img: "cerveja/antarctica_latao_473_ml_.jpg" },
            { id: 26, nome: "Império Pilsen Latão", desc: "473ml", preco: 5.00, img: "cerveja/império_pilsen_puro_malte_latao_473_ml_.jpg" },
            { id: 32, nome: "Brahma Latão", desc: "473ml", preco: 6.00, img: "cerveja/latao_brahma_473_ml.jpg" },
            { id: 33, nome: "Budweiser Latão", desc: "473ml", preco: 6.50, img: "cerveja/latao_budweiser_473_ml_.jpg" },
            { id: 34, nome: "Corona Latão", desc: "473ml", preco: 11.00, img: "cerveja/latao_corona_473_ml_.jpg" },
            { id: 35, nome: "Heineken Latão", desc: "473ml", preco: 8.00, img: "cerveja/latao_heineken_473_ml.jpg" },
            { id: 36, nome: "Império Puro Malte Latão", desc: "473ml", preco: 5.00, img: "cerveja/latao_imperio_puro_malte_473_ml_.jpg" },
            { id: 37, nome: "Itaipava Latão", desc: "473ml", preco: 5.00, img: "cerveja/latao_itaipava_473_ml_.jpg" },
            { id: 38, nome: "Lokal Latão", desc: "473ml", preco: 3.99, img: "cerveja/latao_lokal_473_ml_.jpg" },
            { id: 39, nome: "Original Latão", desc: "473ml", preco: 7.00, img: "cerveja/latao_original_473_ml_.jpg" },
            { id: 40, nome: "Petra Latão", desc: "473ml", preco: 5.00, img: "cerveja/latao_petra_473_ml_.jpg" },
            { id: 41, nome: "Spaten Latão", desc: "473ml", preco: 6.50, img: "cerveja/latao_spaten_473_ml_.jpg" },
            { id: 42, nome: "Stella Artois Latão", desc: "473ml", preco: 7.00, img: "cerveja/latao_stella_artois_puro_malte_473_ml_.jpg" },
            { id: 50, nome: "Skol Latão", desc: "473ml", preco: 6.00, img: "cerveja/skol_473_ml_.jpg" },
            { id: 57, nome: "Eisenbahn Latão", desc: "473ml", preco: 6.00, img: "cerveja/eisenbahn_pilsen_473_ml_.jpg" },
            { id: 9, nome: "Brahma Zero Álcool", desc: "350ml", preco: 5.00, img: "cerveja/brahma_zero_alcool_350_ml_.jpg" },
            { id: 28, nome: "Antarctica Lata", desc: "350ml", preco: 4.50, img: "cerveja/lata_antarctica_350_ml_.jpg" },
            { id: 58, nome: "Brahma Lata", desc: "350ml", preco: 6.00, img: "cerveja/lata_brahma_350_ml_.jpg" },
            { id: 29, nome: "Budweiser Lata", desc: "350ml", preco: 5.00, img: "cerveja/lata_budweiser_350_ml.jpg" },
            { id: 30, nome: "Itaipava Lata", desc: "350ml", preco: 4.00, img: "cerveja/lata_itaipava_350_ml_.jpg" },
            { id: 31, nome: "Original Lata", desc: "350ml", preco: 5.00, img: "cerveja/lata_original_350_ml_.jpg" },
            { id: 49, nome: "Skol Lata", desc: "350ml", preco: 4.50, img: "cerveja/skol_350_ml_.jpg" },
            { id: 3, nome: "Amstel Long Neck", desc: "330ml", preco: 5.00, img: "cerveja/amstel_Long_Neck_330_ml_.jpg" },
            { id: 12, nome: "Budweiser Long Neck", desc: "330ml", preco: 6.00, img: "cerveja/budweiser_long_neck_.jpg" },
            { id: 19, nome: "Corona Long Neck", desc: "330ml", preco: 10.00, img: "cerveja/corona_Long_neck_330_ml_.jpg" },
            { id: 21, nome: "Eisenbahn Long Neck", desc: "330ml", preco: 6.00, img: "cerveja/eisenbahn_long_neck_.jpg" },
            { id: 23, nome: "Heineken Long Neck", desc: "330ml", preco: 8.00, img: "cerveja/heineken_long_neck_330_ml_.jpg" },
            { id: 54, nome: "Spaten Long Neck", desc: "330ml", preco: 7.00, img: "cerveja/spaten_puro_malte_long_neck_.jpg" },
            { id: 55, nome: "Stella Artois Long Neck", desc: "330ml", preco: 8.00, img: "cerveja/stella_artois_puro_malte_long_neck_.jpg" },
            { id: 4, nome: "Antarctica 300ml", desc: "Garrafa", preco: 3.50, img: "cerveja/antarctica_300_ml_.jpg" },
            { id: 7, nome: "Brahma 300ml", desc: "Garrafa", preco: 3.50, img: "cerveja/Brahma_300_ml_.jpg" },
            { id: 10, nome: "Budweiser 300ml", desc: "Garrafa", preco: 3.50, img: "cerveja/budweiser_300_ml_.jpg" },
            { id: 46, nome: "Original 300ml", desc: "Garrafa", preco: 4.50, img: "cerveja/original_300_ml_.jpg" },
            { id: 48, nome: "Skol 300ml", desc: "Garrafa", preco: 3.50, img: "cerveja/skol_300_ml_.jpg" },
            { id: 56, nome: "Itaipava 300ml", desc: "Garrafa", preco: 3.00, img: "cerveja/itaipava_300_ml_.jpg" }
        ]
    },
    {
        id: "energeticos",
        nome: "Energéticos",
        itens: [
            { id: 1301, nome: "Red Hot Original 2L", desc: "Pet", preco: 12.00, img: "energeticos/Red_hot_original_2_L_.jpg" },
            { id: 1310, nome: "Red Hot Melancia 2L", desc: "Pet", preco: 12.00, img: "energeticos/red_hot_melancia_2_L_.jpg" },
            { id: 1312, nome: "Red Hot Maçã Verde 2L", desc: "Pet", preco: 12.00, img: "energeticos/red_hot_maçã_verde_2_L_.jpg" },
            { id: 1313, nome: "Bally Coco com Açaí 2L", desc: "Pet", preco: 16.00, img: "energeticos/baly_coco_com_açaí_2_L_.jpg" },
            { id: 1302, nome: "Attivus 2L", desc: "Pet", preco: 10.00, img: "energeticos/attivus_2_L_.jpg" },
            { id: 1304, nome: "Monster Energy 473ml", desc: "Lata", preco: 12.00, img: "energeticos/monster_energy_473_ml_.jpg" },
            { id: 1305, nome: "Monster Energy Zero 473ml", desc: "Lata", preco: 12.00, img: "energeticos/monster_energy_zero_473_ml_.jpg" },
            { id: 1306, nome: "Monster Mango Loco 473ml", desc: "Lata", preco: 12.00, img: "energeticos/monster_mango_loco_473_ml_.jpg" },
            { id: 1307, nome: "Monster Ultra Fiesta 473ml", desc: "Lata", preco: 12.00, img: "energeticos/monster_ultra_fiesta_437_ml_.jpg" },
            { id: 1308, nome: "Monster Ultra Melancia 473ml", desc: "Lata", preco: 12.00, img: "energeticos/monster_ultra_melancia_473_ml_.jpg" },
            { id: 1309, nome: "Monster Ultra Violet 473ml", desc: "Lata", preco: 12.00, img: "energeticos/monster_ultra_violet_473_ml_.jpg" },
            { id: 1303, nome: "Bally Melancia 473ml", desc: "Lata", preco: 6.00, img: "energeticos/baly_melancia_473_ml_.jpg" },
            { id: 1314, nome: "Red Bull Energy Drink", desc: "Lata 250ml", preco: 10.00, img: "energeticos/red_bull.jpg" },
            { id: 1315, nome: "Red Bull Melancia", desc: "Lata 250ml", preco: 10.00, img: "energeticos/red_bull_melancia.jpg" },
            { id: 1316, nome: "Red Bull Morango e Pêssego", desc: "Lata 250ml", preco: 10.00, img: "energeticos/red_bull_morando_e_pessego.jpg" },
            { id: 1311, nome: "Fontt 200ml", desc: "Garrafa", preco: 4.00, img: "energeticos/fontt_200_ml_.jpg" }
        ]
    },
    {
        id: "drinks",
        nome: "Drinks",
        itens: [
            { id: 1210, nome: "Chopp de Vinho 2L", desc: "Garrafa", preco: 29.00, img: "drinks/choop_de_vinho_2_L_ml_.jpg" },
            { id: 1209, nome: "Chopp de Vinho 600ml", desc: "Garrafa", preco: 9.00, img: "drinks/choop_de_vinho_600_ml_.jpg" },
            { id: 1202, nome: "Beats Senses LN 269ml", desc: "Vidro", preco: 10.00, img: "drinks/beats_senses_vidro_269_ml_.jpg" },
            { id: 1204, nome: "Beats GT LN 269ml", desc: "Vidro", preco: 10.00, img: "drinks/beats_gt_vidro_269_ml_.jpg" },
            { id: 1201, nome: "Beats Senses 269ml", desc: "Lata", preco: 9.00, img: "drinks/beats_senses_269_ml_.jpg" },
            { id: 1203, nome: "Beats GT 269ml", desc: "Lata", preco: 9.00, img: "drinks/beats_gt_269_ml_.jpg" },
            { id: 1205, nome: "Beats Red Mix 269ml", desc: "Lata", preco: 9.00, img: "drinks/beats_red_mix_269_ml_.jpg" },
            { id: 1211, nome: "Beats Tropical 269ml", desc: "Lata", preco: 9.00, img: "drinks/beats_tropical_269_ml_lata_.jpg" },
            { id: 1206, nome: "Ice Kovak 275ml", desc: "Garrafa", preco: 7.00, img: "drinks/ice_kovak_275_ml_.jpg" },
            { id: 1208, nome: "Pink Moon Rosé 300ml", desc: "Garrafa", preco: 6.00, img: "drinks/pink_moon_rosé_300_ml_.jpg" },
            { id: 1207, nome: "Ice Syn 300ml", desc: "Garrafa", preco: 4.00, img: "drinks/ice_syn_300_ml_.jpg" }
        ]
    },
    {
        id: "gelo",
        nome: "Gelo",
        itens: [
            { id: 902, nome: "Gelo em Cubo 5kg", desc: "Saco", preco: 15.00, img: "gelo/saco_gelo_5_kg.jpg" },
            { id: 901, nome: "Gelo em Cubo 2,5kg", desc: "Saco", preco: 12.00, img: "gelo/saco_gelo_2,5_kg_.jpg" },
            { id: 903, nome: "Gelo Saborizado Água de Coco", desc: "Gelo Saborizado", preco: 4.00, img: "gelo/gelo_saborizado_agua_de_coco _.jpg" },
            { id: 904, nome: "Gelo Saborizado Maçã Verde", desc: "Gelo Saborizado", preco: 4.00, img: "gelo/gelo_saborizado_maça_verde_.jpg" },
            { id: 905, nome: "Gelo Saborizado Maracujá", desc: "Gelo Saborizado", preco: 4.00, img: "gelo/gelo_saborizado_maracuja_.jpg" },
            { id: 906, nome: "Gelo Saborizado Melancia", desc: "Gelo Saborizado", preco: 4.00, img: "gelo/gelo_saborizado_melancia_.jpg" },
            { id: 907, nome: "Gelo Saborizado Morango", desc: "Gelo Saborizado", preco: 4.00, img: "gelo/gelo_saborizado_morango_.jpg" },
            { id: 908, nome: "Gelo Saborizado Uva", desc: "Gelo Saborizado", preco: 4.00, img: "gelo/gelo_saborizado_uva_ .jpg" }
        ]
    },
    {
        id: "refrigerantes",
        nome: "Refrigerantes",
        itens: [
            { id: 1009, nome: "Coca-Cola 2L Descartável", desc: "Pet", preco: 12.00, img: "refrigerantes/coca_cola_descartável_2_L_.jpg" },
            { id: 1008, nome: "Coca-Cola 2L Retornável", desc: "Pet", preco: 9.00, img: "refrigerantes/Coca_Cola_retornável 2L.jpg" },
            { id: 1014, nome: "Coca-Cola Zero 2L Retornável", desc: "Pet", preco: 9.00, img: "refrigerantes/coca_cola_zero_retornáve_2_L_.jpg" },
            { id: 1016, nome: "Fanta Laranja 2L Retornável", desc: "Pet", preco: 9.00, img: "refrigerantes/fanta_laranja_retornável_2_L_.jpg" },
            { id: 1018, nome: "Fanta Uva 2L Retornável", desc: "Pet", preco: 9.00, img: "refrigerantes/fanta_uva_retornável_2_L_.jpg" },
            { id: 1027, nome: "Fanta Uva 2L Descartável", desc: "Pet", preco: 12.00, img: "refrigerantes/fanta_uva_retornável_2_L_.jpg" },
            { id: 1028, nome: "Fanta Laranja 2L Descartável", desc: "Pet", preco: 12.00, img: "refrigerantes/fanta_laranja_retornável_2_L_.jpg" },
            { id: 1025, nome: "Mantiqueira 2L", desc: "Pet", preco: 7.00, img: "refrigerantes/mantiqueira_2_L_.jpg" },
            { id: 1026, nome: "Guaraná Antarctica 2L", desc: "Pet", preco: 10.00, img: "refrigerantes/guarana_antarctica_2_L_.jpg" },
            { id: 1007, nome: "Coca-Cola 1,5L", desc: "Pet", preco: 9.00, img: "refrigerantes/coca_cola_1,5_lt_.jpg" },
            { id: 1006, nome: "Coca-Cola 1L Retornável", desc: "Vidro", preco: 7.00, img: "refrigerantes/coca_cola_1_L_retornável_.jpg" },
            { id: 1005, nome: "Coca-Cola 600ml", desc: "Pet", preco: 6.00, img: "refrigerantes/coca_cola_600_ml_.jpg" },
            { id: 1013, nome: "Coca-Cola Zero 600ml", desc: "Pet", preco: 6.00, img: "refrigerantes/coca_cola_zero_600_ml_.jpg" },
            { id: 1004, nome: "Coca-Cola 350ml", desc: "Lata", preco: 5.00, img: "refrigerantes/coca_cola_350_ml_.jpg" },
            { id: 1012, nome: "Coca-Cola Zero 350ml", desc: "Lata", preco: 5.00, img: "refrigerantes/coca_cola_zero_350_ml_.jpg" },
            { id: 1022, nome: "Sprite 350ml", desc: "Lata", preco: 5.00, img: "refrigerantes/sprite_350_ml_.jpg" },
            { id: 1023, nome: "Sprite Zero 350ml", desc: "Lata", preco: 5.00, img: "refrigerantes/sprite_zero_350_ml_.jpg" },
            { id: 1019, nome: "Fys Guaraná Zero 350ml", desc: "Lata", preco: 5.00, img: "refrigerantes/fys_zero_guaraná_350_ml_.jpg" },
            { id: 1020, nome: "Ice Tea Leão com Gás", desc: "Lata", preco: 4.00, img: "refrigerantes/ice_tea_leão_com_gás_.jpg" },
            { id: 1024, nome: "Mate Leão Limão 290ml", desc: "Copo", preco: 4.00, img: "refrigerantes/mate_limão_290_ml_.jpg" },
            { id: 1011, nome: "Coca-Cola Zero 220ml", desc: "Lata", preco: 3.50, img: "refrigerantes/coca_cola_zero_220_ml_.jpg_.jpg" },
            { id: 1003, nome: "Coca-Cola 220ml", desc: "Lata Rose", preco: 3.00, img: "refrigerantes/coca_cola_220_ml_.jpg" },
            { id: 1015, nome: "Fanta Laranja 220ml", desc: "Lata", preco: 3.00, img: "refrigerantes/fanta_laranja_220_ml_.jpg" },
            { id: 1017, nome: "Fanta Uva 220ml", desc: "Lata", preco: 3.00, img: "refrigerantes/fanta_uva_220_ml_.jpg" },
            { id: 1021, nome: "Sprite 220ml", desc: "Lata", preco: 3.00, img: "refrigerantes/sprite_220_ml_.jpg" },
            { id: 1001, nome: "Coca-Cola 200ml", desc: "Pet", preco: 3.00, img: "refrigerantes/coca_cola_200_ml_.jpg" },
            { id: 1010, nome: "Coca-Cola Zero 200ml", desc: "Pet", preco: 3.00, img: "refrigerantes/coca_cola_zero_220_ml_.jpg_.jpg" }
        ]
    },
    {
        id: "sucos",
        nome: "Sucos",
        itens: [
            { id: 1107, nome: "Ativ Plus Guaraná 2L", desc: "Garrafa", preco: 4.50, img: "sucos/ativ_plus_guaraná_2_L_.jpg" },
            { id: 1108, nome: "Ativ Plus Laranja 2L", desc: "Garrafa", preco: 4.50, img: "sucos/ativ_plus_laranja_2_L_.jpg" },
            { id: 1109, nome: "Ativ Plus Limão 2L", desc: "Garrafa", preco: 4.50, img: "sucos/ativ_plus_limão_2_L_.jpg" },
            { id: 1110, nome: "Ativ Plus Uva 2L", desc: "Garrafa", preco: 4.50, img: "sucos/ativ_plus_uva_2_L_.jpg" },
            { id: 1114, nome: "H2O Limão 1,5L", desc: "Garrafa", preco: 10.00, img: "sucos/h_2_o_1,5_L_.jpg" },
            { id: 1115, nome: "Limoneto 1,5L", desc: "Garrafa", preco: 10.00, img: "sucos/limoneto_1,5_L_.jpg" },
            { id: 1105, nome: "Guaraviton Açaí 500ml", desc: "Garrafa", preco: 4.00, img: "sucos/guaraviton_açaí_500_ml_.jpg" },
            { id: 1106, nome: "Guaraviton Ginseng 500ml", desc: "Garrafa", preco: 4.00, img: "sucos/guaraviton_ginseng_500_ml_.jpg" },
            { id: 1112, nome: "H2O Limão 500ml", desc: "Garrafa", preco: 6.00, img: "sucos/h2o_500_ml_.jpg" },
            { id: 1113, nome: "Limoneto 500ml", desc: "Garrafa", preco: 6.00, img: "sucos/limoneto_500_ml_.jpg" },
            { id: 1101, nome: "Guaravita 290ml", desc: "Copo", preco: 2.00, img: "sucos/guaravita_290_ml_.jpg" },
            { id: 1102, nome: "Ativ Plus Guaraná 290ml", desc: "Copo", preco: 1.50, img: "sucos/ativ_plus_Guaraná_290_ml_.jpg" },
            { id: 1103, nome: "Ativ Plus Guaraná com Açaí 290ml", desc: "Copo", preco: 1.50, img: "sucos/ativ_plus_guarána_açaí_290_ml_.jpg" },
            { id: 1104, nome: "Ativ Plus Laranja/Acerola 290ml", desc: "Copo", preco: 1.50, img: "sucos/ativ_plus_laranja_acerola_290_ml_.jpg" }
        ]
    },
    {
        id: "combos",
        nome: "Combos",
        itens: [
            { id: 2001, nome: "Combo Red Label + Red Hot", desc: "1 Whisky Red Label + 1 Red Hot 2L + 3 Gelos Saborizados", preco: 122.00, img: "combos/red_label_+_red+hot_2_L_+_3_gelos_saborizados_.jpg" },
            { id: 2002, nome: "Combo Red Label + Attivus", desc: "1 Whisky Red Label + 1 Attivus 2L + 3 Gelos Saborizados", preco: 120.00, img: "combos/red_label_+_attivus_2_L_+_3_gelos_saborizados_.jpg" },
            { id: 2003, nome: "Combo White Horse + Red Hot", desc: "1 Whisky White Horse + 1 Red Hot 2L + 3 Gelos Saborizados", preco: 112.00, img: "combos/whitehorse_+_red_hot_2_L_+_3_gelos_saborizados_.jpg" },
            { id: 2004, nome: "Combo White Horse + Attivus", desc: "1 Whisky White Horse + 1 Attivus 2L + 3 Gelos Saborizados", preco: 110.00, img: "combos/white_horse_+_attivus_2_L_+_ 3_gelos_saborizados_.jpg" },
            { id: 2005, nome: "Combo Smirnoff + Red Hot", desc: "1 Vodka Smirnoff + 1 Red Hot 2L + 3 Gelos Saborizados", preco: 72.00, img: "combos/smirnoff_+_red_hot_2_L_+_3_gelos_saborizados_.jpg" },
            { id: 2006, nome: "Combo Smirnoff + Attivus", desc: "1 Vodka Smirnoff + 1 Attivus 2L + 3 Gelos Saborizados", preco: 70.00, img: "combos/smirnoff_+_attivus_2_L_+_3_gelos_daborizados_.jpg" },
            { id: 2007, nome: "Combo Royal Blue + Red Hot", desc: "1 Whisky Royal Blue + 1 Red Hot 2L + 3 Gelos Saborizados", preco: 50.00, img: "combos/royal_blue_+_red_hot_2_L_+_3_gelos_saborizados_.jpg" },
            { id: 2008, nome: "Combo Leonoff + Red Hot", desc: "1 Vodka Leonoff + 1 Red Hot 2L + 3 Gelos Saborizados", preco: 42.00, img: "combos/leonoff_+_red_hot_2_L_+_3+gelos_saborizados_.jpg" },
            { id: 2009, nome: "Combo Leonoff + Attivus", desc: "1 Vodka Leonoff + 1 Attivus 2L + 3 Gelos Saborizados", preco: 40.00, img: "combos/leonoff_+_attivus_2_L_+_3_gelos_saborizados_.jpg" },
            { id: 2014, nome: "Whisky + Combo Tigrinho", desc: "1L Coquetel + Energético", preco: 25.00, img: "combos/whisky_+_combo_tigrinho_1_L.jpg" },
            { id: 2015, nome: "Whisky + Combo Maçã Verde", desc: "1L Coquetel + Energético", preco: 25.00, img: "combos/whisky_+_combo_maça_verde_1_L.jpg" },
            { id: 2010, nome: "Combo Corote Vodka", desc: "1L Gaseificado", preco: 20.00, img: "combos/combo_corote_vodka_.jpg" },
            { id: 2011, nome: "Combo Corote Whisky", desc: "1L Gaseificado", preco: 20.00, img: "combos/combo_corote_wisky_.jpg" },
            { id: 2012, nome: "Combo Corote Gin Melancia", desc: "1L Gaseificado", preco: 20.00, img: "combos/combo_corote_gin_melancia_.jpg" },
            { id: 2013, nome: "Combo Corote Gin Tropical", desc: "1L Gaseificado", preco: 20.00, img: "combos/combo_corote_gin_tropical_.jpg" }
        ]
    }
];